export const LOAD_ARTICLES = "LOAD_ARTICLES";
export const LOAD_ARTICLES_ERROR = "LOAD_ARTICLES_ERROR";
export const LOAD_ARTICLES_LOADING = "LOAD_ARTICLES_LOADING";

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const SET_CURRENT_TAG = "SET_CURRENT_TAG";

export const VIEW_ARTICLE = "VIEW_ARTICLE";
export const VIEW_ARTICLE_LOADING = "VIEW_ARTICLE_LOADING";
export const VIEW_ARTICLE_ERROR = "VIEW_ARTICLE_ERROR";

export const FETCH_USER_LOADING = "FETCH_USER_LOADING";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

// export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
// export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const UPDATE_USER = "UPDATE_USER";
export const REGISTER_USER = "REGISTER_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";

export const FETCH_PROFILE_LOADING = "FETCH_PROFILE_LOADING";
export const FETCH_PROFILE_ERROR = "FETCH_PROFILE_ERROR";
export const FETCH_PROFILE = "FETCH_PROFILE";

export const FETCH_COMMENTS_LOADING = "FETCH_COMMENTS_LOADING";
export const FETCH_COMMENTS_ERROR = "FETCH_COMMENTS_ERROR";
export const FETCH_COMMENTS = "FETCH_COMMENTS";

export const FAVORITE_ARTICLE_FETCHING = "FAVORITE_ARTICLE_FETCHING";
export const FAVORITE_ARTICLE_ERROR = "FAVORITE_ARTICLE_ERROR";
export const FAVORITE_ARTICLE = "FAVORITE_ARTICLE";

export const FETCH_AUTHOR_LIST_LOADING = "FETCH_AUTHOR_LIST_LOADING";
export const FETCH_AUTHOR_LIST_ERROR = "FETCH_AUTHOR_LIST_ERROR";
export const FETCH_AUTHOR_LIST = "FETCH_AUTHOR_LIST";

export const EDIT_ARTICLE_FETCHING = "EDIT_ARTICLE_FETCHING";
export const EDIT_ARTICLE_ERROR = "EDIT_ARTICLE_ERROR";
export const EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLE_SUCCESS";